#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Fields
version:      0.16
version_from: lib/Class/Fields.pm
installdirs:  perl
requires:
    constant:                      0
    Carp::Assert:                  0
    Carp:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
